# Generated by Django 2.1.5 on 2019-02-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='this', max_length=60),
            preserve_default=False,
        ),
    ]
