# Generated by Django 3.0.1 on 2019-12-26 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_auto_20190223_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_date',
            field=models.DateField(default=datetime.date(2019, 12, 26)),
        ),
    ]
