# Generated by Django 3.0.1 on 2019-12-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0007_auto_20191227_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='net_sales',
            field=models.DecimalField(decimal_places=2, max_digits=38, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, max_digits=38, null=True),
        ),
    ]
