# Generated by Django 3.0.1 on 2019-12-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0008_auto_20191227_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=38),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='net_sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True),
        ),
    ]
