# Generated by Django 3.0.1 on 2019-12-28 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0009_auto_20191227_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_id']},
        ),
        migrations.RenameField(
            model_name='lineitem',
            old_name='cost',
            new_name='subtotal',
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_date',
            field=models.DateField(default=datetime.date(2019, 12, 28)),
        ),
    ]
